GET http://localhost:3000/api/blogs
###
GET http://localhost:3000/api/blogs/654d6723bd8592e93d046a84
###
DELETE http://localhost:3000/api/blogs/654d6723bd8592e93d046a84
###
POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "Update this book",
    "author": "me",
    "url": "dsfa",
    "likes": 0
}

###
PUT http://localhost:3000/api/blogs/654d6723bd8592e93d046a84
Content-Type: application/json

{
    "title": "Book updated",
    "author": "me again",
    "url": "localhost",
    "likes": 1
}