POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Update",
    "number": 5756765
}
###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/650b0c2af194fcd7cc9d9c65

###
DELETE http://localhost:3001/api/persons/650afe86db24f11f86910171

###
PUT http://localhost:3001/api/persons/650afeb0db24f11f86910180
Content-Type: application/json

{
    "name": "NewName Updated",
    "number": 567567657
}
