GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Harry potter",
    "author": "J.K Rowling",
    "url": "https://es.wikipedia.org/wiki/Harry_Potter",
    "likes": 10
}